//! QUIC direct-connect layer (quinn): where "dial by public key, not by IP" lands
//!
//! Key design (isomorphic to iroh):
//! - Nodes self-sign certificates, **certificate public key == NodeId (identity public key)**; no CA, no SAN validation
//! - A custom rustls certificate verifier extracts the ed25519 public key from the certificate DER;
//!   the connecting side pins it exactly to the expected NodeId; the server side only checks structural validity
//! - The TLS 1.3 handshake itself authenticates identity using the certificate private key
//!   (CertificateVerify is signature-verified by the verifier)
//! - simultaneous-open: both sides act as client and server on the same UDP socket;
//!   the first to establish wins, duplicate connections are deduplicated

use std::io;
use std::net::SocketAddr;
use std::sync::Arc;

use quinn::crypto::rustls::{QuicClientConfig, QuicServerConfig};
use rustls::client::danger::{HandshakeSignatureValid, ServerCertVerified, ServerCertVerifier};
use rustls::pki_types::{CertificateDer, PrivateKeyDer, PrivatePkcs8KeyDer, ServerName, UnixTime};
use rustls::server::danger::{ClientCertVerified, ClientCertVerifier};
use rustls::{DigitallySignedStruct, DistinguishedName, SignatureScheme};

use crate::identity::{verify, NodeId, NodeIdentity};

pub const ALPN: &[u8] = b"p2p-mesh/0";

pub type BoxErr = Box<dyn std::error::Error + Send + Sync>;

/// ed25519 public key SPKI prefix inside the X.509 certificate DER (fixed 12 bytes)
const ED25519_SPKI_PREFIX: [u8; 12] = [
    0x30, 0x2a, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x03, 0x21, 0x00,
];

/// Hand-build a PKCS#8 v2 DER from the ed25519 seed + public key (fixed template; avoids a pkcs8 feature dependency)
fn pkcs8_v2_der(seed: &[u8; 32], pubkey: &[u8; 32]) -> Vec<u8> {
    let mut der = Vec::with_capacity(102);
    der.extend_from_slice(&[
        0x30, 0x53, // SEQUENCE, len=83
        0x02, 0x01, 0x01, // INTEGER 1 (v2)
        0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, // algid: OID 1.3.101.112
        0x04, 0x22, 0x04, 0x20, // OCTET STRING { OCTET STRING { seed } }
    ]);
    der.extend_from_slice(seed);
    der.extend_from_slice(&[0xa1, 0x23, 0x03, 0x21, 0x00]); // [1] { BIT STRING { pubkey } }
    der.extend_from_slice(pubkey);
    der
}

/// Extract the ed25519 public key (= NodeId) from the certificate DER
///
/// The MVP uses prefix scanning instead of full X.509 parsing (certificates are generated by
/// this stack's rcgen, so the structure is fixed). Known debt: switch to x509-parser for
/// canonical parsing.
pub fn extract_node_id(cert: &CertificateDer<'_>) -> Option<NodeId> {
    let der: &[u8] = cert.as_ref();
    let pos = der
        .windows(ED25519_SPKI_PREFIX.len())
        .position(|w| w == ED25519_SPKI_PREFIX)?;
    let key: [u8; 32] = der.get(pos + 12..pos + 44)?.try_into().ok()?;
    Some(NodeId::from_bytes(key))
}

/// Generate a self-signed node certificate (certificate public key == identity public key)
pub fn node_cert(
    identity: &NodeIdentity,
) -> Result<(CertificateDer<'static>, PrivateKeyDer<'static>), BoxErr> {
    let seed = identity.seed_bytes();
    let pk = identity.node_id();
    let der = pkcs8_v2_der(&seed, pk.as_bytes());
    let kp = rcgen::KeyPair::from_pkcs8_der_and_sign_algo(
        &PrivatePkcs8KeyDer::from(der.clone()),
        &rcgen::PKCS_ED25519,
    )?;
    let params = rcgen::CertificateParams::new(vec!["node.p2p-mesh.local".to_string()])?;
    let cert = params.self_signed(&kp)?;
    Ok((
        CertificateDer::from(cert.der().to_vec()),
        PrivateKeyDer::Pkcs8(PrivatePkcs8KeyDer::from(der)),
    ))
}

/// Verify the TLS1.3 CertificateVerify (message context is assembled by rustls)
fn verify_tls13(
    message: &[u8],
    cert: &CertificateDer<'_>,
    dss: &DigitallySignedStruct,
) -> Result<HandshakeSignatureValid, rustls::Error> {
    if dss.scheme != SignatureScheme::ED25519 {
        return Err(rustls::Error::General("only ed25519 certificates are supported".into()));
    }
    let id = extract_node_id(cert)
        .ok_or_else(|| rustls::Error::General("certificate is missing an ed25519 public key".into()))?;
    let sig: [u8; 64] = dss
        .signature()
        .try_into()
        .map_err(|_| rustls::Error::General("invalid signature length".into()))?;
    if !verify(&id, message, &sig) {
        return Err(rustls::Error::General("CertificateVerify signature verification failed".into()));
    }
    Ok(HandshakeSignatureValid::assertion())
}

/// Client verifier: pins the expected peer NodeId (the core of "dial by public key")
#[derive(Debug)]
pub struct NodeServerVerifier {
    expected: NodeId,
}

impl ServerCertVerifier for NodeServerVerifier {
    fn verify_server_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        _now: UnixTime,
    ) -> Result<ServerCertVerified, rustls::Error> {
        let id = extract_node_id(end_entity)
            .ok_or_else(|| rustls::Error::General("peer certificate is missing an ed25519 public key".into()))?;
        if id != self.expected {
            return Err(rustls::Error::General(format!(
                "peer identity mismatch: expected {} got {}",
                self.expected, id
            )));
        }
        Ok(ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        Err(rustls::Error::General("QUIC uses TLS 1.3 only".into()))
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        verify_tls13(message, cert, dss)
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        vec![SignatureScheme::ED25519]
    }
}

/// Server verifier: accepts any structurally valid node certificate (identity is extracted as peer_identity after the handshake)
#[derive(Debug)]
pub struct NodeClientVerifier;

impl ClientCertVerifier for NodeClientVerifier {
    fn offer_client_auth(&self) -> bool {
        true
    }

    fn client_auth_mandatory(&self) -> bool {
        true
    }

    fn root_hint_subjects(&self) -> &[DistinguishedName] {
        &[]
    }

    fn verify_client_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _now: UnixTime,
    ) -> Result<ClientCertVerified, rustls::Error> {
        extract_node_id(end_entity)
            .ok_or_else(|| rustls::Error::General("client certificate is missing an ed25519 public key".into()))?;
        Ok(ClientCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        Err(rustls::Error::General("QUIC uses TLS 1.3 only".into()))
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        verify_tls13(message, cert, dss)
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        vec![SignatureScheme::ED25519]
    }
}

/// Build the client QUIC config (pins expected_peer)
pub fn client_config(
    identity: &NodeIdentity,
    expected_peer: NodeId,
) -> Result<quinn::ClientConfig, BoxErr> {
    let (cert, key) = node_cert(identity)?;
    let mut cc = rustls::ClientConfig::builder()
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(NodeServerVerifier { expected: expected_peer }))
        .with_client_auth_cert(vec![cert], key)?;
    cc.alpn_protocols = vec![ALPN.to_vec()];
    Ok(quinn::ClientConfig::new(Arc::new(QuicClientConfig::try_from(cc)?)))
}

/// Build the server QUIC config (requires a client certificate)
pub fn server_config(identity: &NodeIdentity) -> Result<quinn::ServerConfig, BoxErr> {
    let (cert, key) = node_cert(identity)?;
    let mut sc = rustls::ServerConfig::builder()
        .with_client_cert_verifier(Arc::new(NodeClientVerifier))
        .with_single_cert(vec![cert], key)?;
    sc.alpn_protocols = vec![ALPN.to_vec()];
    Ok(quinn::ServerConfig::with_crypto(Arc::new(QuicServerConfig::try_from(
        sc,
    )?)))
}

/// Create a QUIC endpoint on the same UDP socket used for hole punching (each side acts as client and server)
pub fn endpoint_from_socket(
    socket: std::net::UdpSocket,
    identity: &NodeIdentity,
) -> Result<quinn::Endpoint, BoxErr> {
    let sc = server_config(identity)?;
    let runtime = quinn::default_runtime().ok_or("no usable async runtime")?;
    Ok(quinn::Endpoint::new(
        quinn::EndpointConfig::default(),
        Some(sc),
        socket,
        runtime,
    )?)
}

/// Extract the peer's NodeId (the peer's certificate public key)
pub fn conn_peer_id(conn: &quinn::Connection) -> Option<NodeId> {
    let any = conn.peer_identity()?;
    let certs = any.downcast::<Vec<CertificateDer<'static>>>().ok()?;
    extract_node_id(certs.first()?)
}

/// Write one message (length-prefixed + payload, then finish)
pub async fn write_msg(conn: &quinn::Connection, payload: &[u8]) -> Result<(), BoxErr> {
    let (mut send, _recv) = conn.open_bi().await?;
    send.write_all(&(payload.len() as u32).to_be_bytes()).await?;
    send.write_all(payload).await?;
    send.finish()?;
    Ok(())
}

/// Read one message from a bi stream
pub async fn read_msg(mut recv: quinn::RecvStream) -> io::Result<Vec<u8>> {
    let mut len_buf = [0u8; 4];
    recv.read_exact(&mut len_buf)
        .await
        .map_err(|e| io::Error::new(io::ErrorKind::UnexpectedEof, e))?;
    let len = u32::from_be_bytes(len_buf) as usize;
    if len > 4 * 1024 * 1024 {
        return Err(io::Error::new(io::ErrorKind::InvalidData, "message too large"));
    }
    let mut buf = vec![0u8; len];
    recv.read_exact(&mut buf)
        .await
        .map_err(|e| io::Error::new(io::ErrorKind::UnexpectedEof, e))?;
    Ok(buf)
}

/// simultaneous-open: both sides connect + accept at once; whoever establishes first wins
///
/// Returns (connection, whether it is an outbound connection). The caller is responsible for dedup.
pub async fn simultaneous_open(
    ep: &quinn::Endpoint,
    identity: &NodeIdentity,
    peer: NodeId,
    peer_addr: SocketAddr,
    retries: u32,
    retry_interval: std::time::Duration,
) -> Result<quinn::Connection, BoxErr> {
    let mut last_err: Option<BoxErr> = None;
    for _ in 0..retries.max(1) {
        let cfg = client_config(identity, peer)?;
        match ep.connect_with(cfg, peer_addr, "node.p2p-mesh.local") {
            Ok(connecting) => match connecting.await {
                Ok(conn) => return Ok(conn),
                Err(e) => last_err = Some(Box::new(e)),
            },
            Err(e) => last_err = Some(Box::new(e)),
        }
        tokio::time::sleep(retry_interval).await;
    }
    Err(last_err.unwrap_or_else(|| "connect failed".into()))
}
